import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import CustomNavbar from './components/CustomNavbar'
import Button from 'react-bootstrap/Button';
import Link from 'next/link';
import Layout from './components/Layout';

const inter = Inter({ subsets: ['latin'] })

// const inter = Inter({ subsets: ['latin'] })

import Card from 'react-bootstrap/Card';

export default function Home() {
  return (
    <>
      <Head>
        <title>Squadron</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.main} ${inter.className}`} style={{backgroundImage: "url('/')", backgroundSize: "cover",}}>
        <div className="d-flex flex-column align-items-center justify-content-center h-100">
          <h1 className="text-black">Welcome to SNU'S One stop Destination</h1>
          <h3 className="text-black"> For info related to Minors and Specialization</h3>

          <div className="row mt-5">
            <div className="col-md-6" style={{marginBottom:'20px'}}>
              <Card>
                <Card.Body>
                  <Card.Title>Minors</Card.Title>
                  <Card.Text>
                    Minors are a great way to explore your interests and expand your knowledge.
                    You can choose a minor from any department except your major department.SNU offers a wide range of minors.
                    Some of the popular minors are:Communication, Computer Science and Design.
                  </Card.Text>
                  
                  <Button variant="primary">
                    <Link href="/MinorInfo" target='_blank' style={{color:'white',textDecoration:'none'}}>More info</Link>
                    
                    </Button>
                </Card.Body>
              </Card>
            </div>
            <div className="col-md-6">
              <Card>
                <Card.Body>
                  <Card.Title>Specialization</Card.Title>
                  <Card.Text>
                    Some courses from your core department are offered as major electives. You can choose to specialize in a particular field by taking these courses.
                    For example a Computer Science Student can specialize in AI/ML or CyberSecurity.
                  </Card.Text>
                  <Button variant="primary">More info</Button>
                </Card.Body>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
